// Fictional inspection records for the 3D equipment scene (WELL-A07).
// `part` must match a component key exported by three/wellhead.js.
// status: pass | attn | crit | na  (see docs/DESIGN_SYSTEM.md colour roles)
// Every finding, report number and date below is demonstration data.

const REPORT = 'FI-DEMO-0214 · SAMPLE FINAL INSPECTION PLATFORM-A #07';
const DATE = '2026-02-11';

export const HOTSPOTS = [
  {
    id: 'swab',
    part: 'swab',
    component: 'Swab valve',
    category: 'Valve maintenance',
    result: 'Hard to operate before grease; operates after grease',
    outcome: 'Operable after maintenance',
    severity: 'None',
    status: 'pass',
    date: DATE,
    source: `${REPORT} · Swab Valve`,
    followUp: 'Keep in the routine greasing scope.',
    nextVisit: 'Routine interval · 2026-08',
    evidence: 'Record validated automatically',
  },
  {
    id: 'upperMaster',
    part: 'upperMaster',
    component: 'Upper master valve',
    category: 'Valve maintenance',
    result: 'Easy to Operate changed Yes → No after grease',
    outcome: 'Requires attention — confirm entry with the crew',
    severity: 'Medium',
    status: 'attn',
    date: DATE,
    source: `${REPORT} · Master Valve 2`,
    followUp: 'Confirm the entry before scoring; re-check operation on the next visit.',
    nextVisit: 'Brought forward · 2026-04',
    evidence: 'Awaiting coordinator confirmation',
  },
  {
    id: 'master',
    part: 'master',
    component: 'Lower master valve',
    category: 'Valve maintenance',
    result: 'Fully opens and closes; easy to operate after grease',
    outcome: 'Verified / operable',
    severity: 'None',
    status: 'pass',
    date: DATE,
    source: `${REPORT} · Master Valve 1`,
    followUp: 'Continue at the routine maintenance interval.',
    nextVisit: 'Routine interval · 2026-08',
    evidence: 'Record validated automatically',
  },
  {
    id: 'wing',
    part: 'wing',
    component: 'Wing valve',
    category: 'Visual inspection',
    result: 'Stem packing leak observed',
    outcome: 'Greased; leak persists after greasing',
    severity: 'Critical',
    status: 'crit',
    date: DATE,
    source: `${REPORT} · Wing Valve 1.1`,
    followUp: 'Raise a corrective work request; prepare packing material before the next trip.',
    nextVisit: 'Corrective queue · next platform trip',
    evidence: 'Field note recorded; photo reference held internally',
  },
  {
    id: 'annulus',
    part: 'annulus',
    component: 'Annulus valve',
    category: 'Leak / barrier test',
    result: 'No test performed on this visit',
    outcome: 'Not tested — excluded from the operable percentage',
    severity: 'Unknown',
    status: 'na',
    date: DATE,
    source: `${REPORT} · B-annulus Valve`,
    followUp: 'Schedule the test on the next due visit; confirm access with operations.',
    nextVisit: 'Next due · 2026-05',
    evidence: 'Insufficient data',
  },
  {
    id: 'flange',
    part: 'flange',
    component: 'Tubing-head adapter',
    category: 'Visual inspection',
    result: 'Surface corrosion on studs and nuts',
    outcome: 'Requires attention — no maintenance action this visit',
    severity: 'Medium',
    status: 'attn',
    date: DATE,
    source: `${REPORT} · Studs / nuts condition`,
    followUp: 'Add stud cleaning and protective coating to the next maintenance scope.',
    nextVisit: 'Next due · 2026-05',
    evidence: 'Recorded in inspection form',
  },
  {
    id: 'gauge',
    part: 'gauge',
    component: 'Pressure gauge',
    category: 'Pressure observation',
    result: 'Tubing pressure reading recorded; gauge in calibration',
    outcome: 'Verified against the pressure mapping table',
    severity: 'None',
    status: 'pass',
    date: DATE,
    source: `${REPORT} · Pressure observation`,
    followUp: 'No action. Reading kept in the visit history for comparison.',
    nextVisit: 'Routine interval · 2026-08',
    evidence: 'Record validated automatically',
  },
  {
    id: 'conductor',
    part: 'conductor',
    component: 'Conductor',
    category: 'Visual inspection',
    result: 'Not in the scope of this visit',
    outcome: 'Not tested — insufficient data',
    severity: 'Unknown',
    status: 'na',
    date: DATE,
    source: `${REPORT} · General information`,
    followUp: 'Note for the integrity review; no field action planned.',
    nextVisit: 'Reviewed at the next SPR period',
    evidence: 'Insufficient data',
  },
];

export const STATUS_LABEL = {
  pass: 'Verified / operable',
  attn: 'Requires attention',
  crit: 'Critical finding',
  na: 'Not tested / insufficient data',
};
