// Fictional inspection records for the 3D equipment scene (WELL-A07).
// `part` must match a component key exported by three/wellhead.js.
// status: pass | attn | crit | na  (see docs/DESIGN_SYSTEM.md colour roles)

const SOURCE = 'SAMPLE FINAL INSPECTION PLATFORM-A #07.xlsx';
const DATE = '2026-02-11';

export const HOTSPOTS = [
  {
    id: 'wing',
    part: 'wing',
    component: 'Production wing valve',
    category: 'Visual inspection',
    result: 'Stem packing leak observed',
    outcome: 'Greased; leak persists after greasing',
    severity: 'Critical',
    status: 'crit',
    date: DATE,
    source: `${SOURCE} · Wing Valve 1.1`,
    followUp: 'Raise a corrective work request and prioritise on the next platform trip.',
    evidence: 'Field note recorded; photo reference held internally',
  },
  {
    id: 'swab',
    part: 'swab',
    component: 'Swab valve',
    category: 'Valve maintenance',
    result: 'Easy to Operate changed Yes → No after grease',
    outcome: 'Needs attention — possible data entry error',
    severity: 'Medium',
    status: 'attn',
    date: DATE,
    source: `${SOURCE} · Swab Valve`,
    followUp: 'Confirm the entry with the crew before scoring; re-check operation on the next visit.',
    evidence: 'Awaiting coordinator confirmation',
  },
  {
    id: 'flange',
    part: 'flange',
    component: 'Tubing head adapter flange',
    category: 'Visual inspection',
    result: 'Surface corrosion on studs and nuts',
    outcome: 'No maintenance action on this visit',
    severity: 'Medium',
    status: 'attn',
    date: DATE,
    source: `${SOURCE} · Studs / nuts condition`,
    followUp: 'Include stud cleaning and protective coating in the next maintenance scope.',
    evidence: 'Recorded in inspection form',
  },
  {
    id: 'master',
    part: 'master',
    component: 'Master valve',
    category: 'Valve maintenance',
    result: 'Fully opens and closes; easy to operate after grease',
    outcome: 'Passed',
    severity: 'None',
    status: 'pass',
    date: DATE,
    source: `${SOURCE} · Master Valve 1`,
    followUp: 'Continue at the routine maintenance interval.',
    evidence: 'Record validated automatically',
  },
  {
    id: 'gauge',
    part: 'gauge',
    component: 'Pressure gauge',
    category: 'Pressure observation',
    result: 'Tubing pressure reading recorded',
    outcome: 'Verified against the pressure observation table',
    severity: 'None',
    status: 'pass',
    date: DATE,
    source: `${SOURCE} · Pressure observation`,
    followUp: 'No action. Keep reading in the visit history for comparison.',
    evidence: 'Record validated automatically',
  },
  {
    id: 'annulus',
    part: 'annulus',
    component: 'Annulus valve',
    category: 'Leak / barrier test',
    result: 'No test performed on this visit',
    outcome: 'No test — excluded from the passed percentage',
    severity: 'Unknown',
    status: 'na',
    date: DATE,
    source: `${SOURCE} · B-annulus Valve`,
    followUp: 'Schedule the test on the next due visit; confirm access with operations.',
    evidence: 'Insufficient data',
  },
  {
    id: 'choke',
    part: 'choke',
    component: 'Production choke',
    category: 'Scoring policy',
    result: 'Reported in the Final Inspection',
    outcome: 'Excluded from scoring by policy',
    severity: 'Not scored',
    status: 'na',
    date: DATE,
    source: `${SOURCE} · Production Choke`,
    followUp: 'None required by the scoring policy; visual remarks remain visible in the record.',
    evidence: 'Reported, not scored',
  },
];

export const STATUS_LABEL = {
  pass: 'Passed / verified',
  attn: 'Requires attention',
  crit: 'Critical finding',
  na: 'No test / insufficient data',
};
